[GLOBAL]
pants_version = "2.14.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["==3.8.*"]
enable_resolves = true

[python.resolves]
  cat_req = "3rdparty/python/cat.lock"
  dog_req = "3rdparty/python/dog.lock"

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[test]
output = "all"

