[anonymous-telemetry]
enabled = false

[GLOBAL]
pants_version = "2.14.0"

backend_packages.add = [
  "pants.backend.python",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
]
build_file_prelude_globs = ["pants-plugins/macros.py"]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = [">=3.8.*,<=3.10.*"]
enable_resolves = true

[python.resolves]
  cat = "3rdparty/python/cat.lock"
  dog = "3rdparty/python/dog.lock"
  tiger = "3rdparty/python/tiger.lock"
  lion = "3rdparty/python/lion.lock"
  duck = "3rdparty/python/duck.lock"

[black]
  version = "black==22.10.0"
  lockfile = "3rdparty/black.lock"

[isort]
  args = ["--profile black", "--order-by-type"]
  version = "isort==5.10.1"
  lockfile = "3rdparty/isort.lock"

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>"]

[test]
output = "all"

